version: '{build}'

environment:
  CHOCO_API_KEY:
    secure: hsyCpvNm18kiTWHdcPSN7PLra8FGfypgnSuviKQMBdY1LGnpjE4//JD1uQ+vnzU5

build_script:
  - choco pack

test_script:
  # install
  - choco install latexml -dv -s "'.;https://chocolatey.org/api/v2/'"
  - choco install wget unzip
  - refreshenv
  - wget https://miktex.org/download/win/miktexsetup-x64.zip
  - unzip miktexsetup-x64.zip
  - setlocal enableextensions
  - md C:\temp\miktex
  - miktexsetup.exe --quiet --local-package-repository=C:\temp\miktex --package-set=basic download
  # test
  - set PATH=C:\Strawberry\perl\bin;%PATH%
  - C:\Strawberry\perl\site\bin\latexml --dest=test.xml test.tex
  - refreshenv
  - if NOT exist test.xml exit 1
  - ps: |
      $found = Select-String -Path $Env:APPVEYOR_BUILD_FOLDER\test.xml -Pattern "ERROR"
      if ($found) {
        exit 1
      }
  # uninstall
  - choco uninstall latexml -y

deploy_script:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") {
        $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
        $pkgVersion = Select-Xml -Path $Env:APPVEYOR_BUILD_FOLDER\latexml.nuspec `
             -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
             -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
        choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
        choco push $Env:APPVEYOR_BUILD_FOLDER\latexml.${pkgVersion}.nupkg -source https://chocolatey.org/
      } else {
        Write-Host Skip deployment for non tag commits
      }

on_finish:
  - ps: Push-AppveyorArtifact $Env:APPVEYOR_BUILD_FOLDER\test.xml
  - ps: Push-AppveyorArtifact C:\ProgramData\chocolatey\logs\chocolatey.log
  - ps: Get-ChildItem C:\Users\appveyor\.cpanm\work\*\build.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.FullName }
