image:https://github.com/metanorma/chocolatey-latexml/workflows/main/badge.svg["Build Status", link="https://github.com/metanorma/chocolatey-latexml/actions?query=workflow%3Amain"]
image:https://img.shields.io/chocolatey/v/latexml.svg["Version", link="https://chocolatey.org/packages/latexml"]
image:https://img.shields.io/chocolatey/dt/latexml.svg["Downloads", link="https://chocolatey.org/packages/latexml"]

= chocolatey-latexml: Chocolatey install for LaTeXML

== Repository purpose

This repository is for developing the official LaTeXML Chocolatey package.
End users should install LaTeXML directly from the official Chocolatey
repository using standard Chocolatey commands.

For end-user installation, see <<Installation from official repository>>.

== Dependencies

The LaTeXML Chocolatey package specifies dependencies in its `nupkg`:

* `strawberryperl` (version 5.28+)

When installing LaTeXML via Chocolatey, the dependency is resolved automatically.


== Modifying the package

. Edit the `latexml.nuspec` configuration file.
. Edit the `./tools/chocolateyinstall.ps1` install script
. Edit the `./tools/chocolateyuninstall.ps1` uninstall script
. You **must** save your files with *UTF-8* character encoding without BOM.


== Building the package

* Run `choco pack` in the same directory as `latexml.nuspec`

NOTE: If you are running this from a command prompt/Powershell prompt, you must run it "`as Administrator`".


== Testing the package

=== Automated testing

The repository includes a PowerShell test script that validates the package structure:

[source,powershell]
----
# Run all test scenarios (Windows)
pwsh -ExecutionPolicy Bypass -File test/test_installation.ps1 -Verbose
----

The test script validates:

* Nuspec file structure and required elements
* Installation and uninstallation script presence
* Strawberry Perl dependency specification
* Error handling in scripts


=== Manual testing

NOTE: Manual testing should be done on a Virtual Machine (See:
https://github.com/chocolatey/chocolatey-test-environment).

In the package directory, use:

* `choco install latexml -dv -s "'$pwd;https://chocolatey.org/api/v2/'" -f` (Powershell)
* `choco install latexml -dv -s "'%cd%;https://chocolatey.org/api/v2/'" -f` (everywhere else)

Or, use the full path:

* `choco install latexml --source 'c:\path\to\package;chocolatey' -f`

NOTE: It is important to include the Chocolatey source in the source list to
ensure remote dependencies can be resolved.

After executing the install, ensure that `latexml` is installed by executing:

[source,sh]
----
latexml --VERSION
----

If it is properly installed, you will see the current version of LaTeXML.


=== Testing uninstallation

NOTE: The Chocolatey install path on Windows is typically `C:\ProgramData\chocolatey`

Execute the following command to uninstall LaTeXML.

[source,sh]
----
choco uninstall latexml -y
----

After executing the uninstall ensure that `latexml` is not found in the
Chocolatey install path.


== Publish the package to the Chocolatey community feed repository

[source,sh]
----
choco apikey -k [API_KEY_HERE] -source https://chocolatey.org/

# package name can be omitted below
choco push latexml.[version num].nupkg -s https://chocolatey.org/
----


== Installation from official repository

[source,sh]
----
choco install latexml -y
----

or

[source,sh]
----
cinst latexml -y
----


== Release process

=== Manual release

. Go to Actions → release-tag workflow
. Click "Run workflow"
. Enter the version (e.g., `0.8.9` or `refs/tags/v0.8.9`)
. The workflow will update `latexml.nuspec` and create a tag
. The tag push triggers the main workflow to build, test, and publish

=== Automatic release

The repository supports `repository_dispatch` events with type `latexml-release`.
To trigger an automatic release from another repository:

[source,json]
----
{
  "event_type": "latexml-release",
  "client_payload": {
    "ref": "refs/tags/v0.8.9"
  }
}
----


== Branch structure

* https://github.com/metanorma/chocolatey-latexml[`main`] branch - for stable releases
* https://github.com/metanorma/chocolatey-latexml/tree/beta[`beta`] branch - for releases from https://github.com/brucemiller/LaTeXML git


See the https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart[Chocolatey Packages Quick Start]
for more information.
