image:https://github.com/metanorma/chocolatey-latexml/workflows/main/badge.svg?branch=beta["Build Status", link="https://github.com/metanorma/chocolatey-latexml/actions?query=workflow%3Amain+branch%3Abeta"]
image:https://img.shields.io/chocolatey/v/latexml.svg["Version", link="https://chocolatey.org/packages/latexml"]
image:https://img.shields.io/chocolatey/dt/latexml.svg["Downloads", link="https://chocolatey.org/packages/latexml"]

= chocolatey-latexml: Chocolatey install for LaTeXML (BETA)

* https://github.com/metanorma/chocolatey-latexml[`master`] branch - for stable releases
* https://github.com/metanorma/chocolatey-latexml/tree/beta[`beta`] branch - for releases from https://github.com/brucemiller/LaTeXML git

== Modifying the package

. Edit the `latexml.nuspec` configuration file.
. Edit the `./tools/chocolateyInstall.ps1` install script
. Edit the `./tools/chocolateyUninstall.ps1` uninstall script
. You **must** save your files with *UTF-8* character encoding without BOM.

== Building the package

* Run `choco pack` in the same directory as `latexml.nuspec`

NOTE: If you are running this from a command prompt/Powershell prompt, you must run it "`as Administrator`".

== Testing the package

NOTE: Testing should be done on a Virtual Machine (See: https://github.com/chocolatey/chocolatey-test-environment)

In the package directory, use:

* `choco install latexml -dv -s "'$pwd;https://chocolatey.org/api/v2/'" -f` (Powershell)
* `choco install latexml -dv -s "'%cd%;https://chocolatey.org/api/v2/'" -f` (everywhere else)

Or, use the full path:

* `choco install latexml -source 'c:\path\to\package' -f`

After executing the install, ensure that `latexml.exe` is installed by executing the following command from the command prompt:

[source,sh]
----
latexml version
----

If it is properly installed, you will see the current version of LaTeXML.

=== Testing uninstallation

NOTE: The Chocolatey install path on Windows is typically `C:\ProgramData\chocolatey`

Execute the following command to uninstall LaTeXML.

[source,sh]
----
choco uninstall latexml -y
----

After executing the uninstall ensure that `latexml` is not found in the Chocolatey install path.

You can also try running `latexml --VERSION` from the command-line to see if it is still installed


== Publish the package to the Chocolatey community feed repository

[source,sh]
----
choco apikey -k [API_KEY_HERE] -source https://chocolatey.org/`

# package name can be omitted below
choco push latexml.[version num].nupkg -s https://chocolatey.org/
----

== Installation from official repository

[source,sh]
----
choco install latexml -y
----

or

[source,sh]
----
cinst latexml -y
----


See the https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart[Chocolatey Packages Quick Start]
for more information.

See the https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart[Chocolatey Packages Quick Start]
for more information.
